routes/web.php
<?php
use App\Http\Controllers\{
    HomeController,AdminController, FileController,
    AdminViewController, HistoryController,
    AuthController,ActivityLoggerController,
    ViewController,
};
use App\Http\Controllers\withAuth\{
    SopController,NewsController,AnnouncementController,
    HcController,
    MatrixTipsController,
    PolicyController,
};
use App\Http\Controllers\withAuth\Superadmin\{
    RegistrationController,ActivityLogController,
    DeleteFileController,UpdatePasswordController,
};
use Illuminate\Support\Facades\Route;
use Stevebauman\Location\Facades\Location;

Route::get('/', function () {
    return redirect('login');
});

Route::get('/login/{q?}', [AuthController::class, 'login'])->name('login');
Route::post('/dologin', [AuthController::class, 'doLogin'])->name('doLogin');
Route::get('/logout', [AuthController::class, 'doLogout'])->name('logout');
Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('auth');
Route::prefix('view')->group(function () {
    Route::group(['prefix' => 'sop', 'as' => 'sop.'],function () {
        Route::get('/', [FileController::class, 'viewSOPAll'])->name('all');
        Route::middleware('private')->group(function () {
            Route::get('{title}', [ViewController::class, 'viewSOP'])->name('title');
            Route::get('{title}/{page}', [ViewController::class, 'viewIdPage'])->name('id.page');
        });

    });


    Route::group(['prefix' => 'news', 'as' => 'news.'],function () {
        Route::get('/', [ViewController::class, 'viewNewsAll'])->name('all');
        Route::get('{title}', [ViewController::class, 'viewNews'])->name('title');
        Route::get('user/{string}', [ViewController::class, 'newsByUser'])->name('newsByUser');
    });
    Route::group(['prefix' => 'announcement', 'as' => 'announcement.'],function () {
        Route::get('/', [ViewController::class, 'viewAnnouncementAll'])->name('all');
        Route::get('{title}', [ViewController::class, 'viewAnnouncement'])->name('title');
    });
    Route::group(['prefix' => 'hc-corner', 'as' => 'hc-corner.'],function () {
        Route::get('/', [ViewController::class, 'viewHCornerAll'])->name('all');
        Route::get('{title}', [ViewController::class, 'viewHCorner'])->name('title');
    });
    Route::group(['prefix' => 'tips', 'as' => 'tips.'],function () {
        Route::get('/', [ViewController::class, 'viewTipsAll'])->name('all');
        Route::get('{title}', [ViewController::class, 'viewTips'])->name('title');
    });
    Route::group(['prefix' => 'policy', 'as' => 'policy.'],function () {
        Route::get('/', [FileController::class, 'viewPolicyAll'])->name('all');
        Route::get('{title}', [ViewController::class, 'viewPolicy'])->name('title');
        Route::get('{title}/{page}', [ViewController::class, 'viewIdPagePolicy'])->name('id.page');
    });
});
Route::get('/sop/dept/{id}', [FileController::class, 'viewSOPDept'])->name('view.sop.dept');

Route::get('/sop/history', [HistoryController::class, 'view'])->name('sop.history');
Route::get('/view/isolate/{string}/{additional?}', [FileController::class, 'isolate']);
Route::get('/view/isolatethumbnail/{string}', [FileController::class, 'isolateThumbnail']);

Route::group(['namespace' => 'withAuth'], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'],function () {
        Route::middleware('dept:rnc')->group(function () {
            Route::group(['prefix' => 'sop', 'as' => 'sop.'],function () {
                    Route::get('upload', [SopController::class, 'uploadView'])->name('form.sop');
                    Route::get('delete', [SopController::class, 'deleteView'])->name('delete.sop');
                    Route::post('upload', [SopController::class, 'fileUpload'])->name('uploadSOP');
                    Route::post('uploadsplit', [SopController::class, 'uploadSplitSOP'])->name('uploadSplitSOP');
            });
            Route::group(['prefix' => 'policy', 'as' => 'policy.'],function () {
                Route::get('upload', [PolicyController::class, 'uploadView'])->name('form.policy');
                Route::post('upload', [PolicyController::class, 'fileUpload'])->name('uploadPolicy');
                Route::post('uploadsplit', [PolicyController::class, 'uploadSplitPolicy'])->name('uploadSplitPolicy');
            });
        });
        Route::middleware('dept:mrc,hcl')->group(function () {
            Route::get('announcement/create', [AnnouncementController::class, 'create'])->name('form.announcement');
        });
        Route::middleware('dept:mrc')->group(function () {
            Route::get('news/create', [NewsController::class, 'createNews'])->name('form.news');
            Route::get('tips/create', [MatrixTipsController::class, 'createTips'])->name('form.tips');
        });
        Route::middleware('dept:hcl')->group(function () {
            Route::get('corner/create', [HcController::class, 'createCorner'])->name('form.corner');
        });
    });
});
Route::group(['namespace' => 'withAuth/Superadmin'], function () {
    Route::get('superadmin/add/user', [RegistrationController::class, 'add'])->name('add.user');
    Route::get('superadmin/update/user/password', [UpdatePasswordController::class, 'update'])->name('update.user');
    Route::get('superadmin/log/activity', [ActivityLogController::class, 'view'])->name('view.activity');
    Route::get('superadmin/delete/unused-file', [DeleteFileController::class, 'ViewDeleteUnusedFile'])->name('delete.unused');
    Route::get('superadmin/delete/unused-file/process', [DeleteFileController::class, 'ProcessDeleteUnusedFile'])->name('delete.unused.process');
});

Route::get('/dummy', [HomeController::class, 'dummy']);
Route::post('/activity-logger', [ActivityLoggerController::class, 'logging'])->name('logger');

app/Http/Livewire/Components/Additional/SuccessNotify.php
<?php

namespace App\Http\Livewire\Components\Additional;
use Livewire\Component;

class SuccessNotify extends Component
{
    public $messages;
    public function render()
    {
        return view('livewire.Components.Additional.success-notify');
    }	
}

app/Http/Livewire/Components/Announcement/CreateAnnouncement.php
<?php

namespace App\Http\Livewire\Components\Announcement;

use Livewire\Component;
use Illuminate\Support\Facades\DB;
use Livewire\WithFileUploads;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Http\Traits\{TextProcessingTrait,LoggerTrait};
use App\Models\{Posts,Announcement,HistorySOP,
    History_desc, Dept,PostUserRel};

class CreateAnnouncement extends Component
{
    use WithFileUploads, TextProcessingTrait, LoggerTrait;
    public $title, $description, $thumbnail, $descriptionPreview, $thumbnailPreview;
    public $createdBy;
    public $preview = false;
    protected $listeners = [
        'refresh-contents' => 'getContent'
    ];
    protected $rules = [
        'title' => 'required|unique:posts,title|max:255',
        'description' => 'required',
        'thumbnail' => 'required|mimes:jpg,jpeg,png|max:2048',
    ];
    private function resetInput()
    {
        $this->title = null;
        $this->description = null;
        $this->thumbnail = null;
        $this->descriptionPreview = null;
        $this->thumbnailPreview = null;
        $this->preview = false;
    }

    public function getContent($term)
    {
        $this->description= $term['content'];
        // clean($this->description)
    }
    public function render()
    {
        // dd(request()->header('Referer'));
        return view('livewire.create-announcement');
    }
    public function submit()
    {
        $this->validate();
        $postModel = new Posts;
        $announcementModel = new Announcement;
        $history = new HistorySOP;
        $user_post = new PostUserRel;
        DB::transaction(function () use (
            $postModel,$history,$announcementModel,$user_post)
            {
                $postModel->title = $this->title;
                $postModel->id_dept = Dept::where('dept_code', 'mrc')->firstOrfail()->id;
                $postModel->seo_url = $this->string_seo($this->title);
                $postModel->save();
                $history->id_post = $postModel->id;
                $history->save();
                // $history_desc->id_history = $history->id;
                // $history_desc->desc = 'first upload';
                // $history_desc->save();
                $fileName = $postModel->id.'-'.$this->seo_friendly_url($this->limit_text($this->title, 6));
                $dom = new \DomDocument();
                $dom->loadHtml($this->description, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
                $images = $dom->getElementsByTagName('img');
                foreach($images as $k => $img){
                    $data = $img->getAttribute('src');
                    list($type, $data) = explode(';', $data);
                    list(, $data)      = explode(',', $data);
                    $data = base64_decode($data);
                    $image_name = '/public/uploads/announcements/'.$fileName.'/contents'.'/'.
                    $fileName.'-'.time().$k.'.png';
                    $path = '/storage/uploads/announcements/'.$fileName.'/contents'.'/'.
                    $fileName.'-'.time().$k.'.png';
                    Storage::put($image_name, $data);
                    $img->removeAttribute('src');
                    $img->setAttribute('src', $path);
                }
                $this->description = $dom->saveHTML();
                $announcementModel->contents = $this->description;
                $announcementModel->id_post = $postModel->id;

                $this->thumbnail->storeAs('uploads/announcements/'.$fileName.'/thumbnail',
                    $fileName.'.'.$this->thumbnail->getClientOriginalExtension(), 'public');

                $announcementModel->thumbnail_path = '/storage/uploads/announcements/'.$fileName.'/thumbnail/'.
                    $fileName.'.'.$this->thumbnail->getClientOriginalExtension();
                $announcementModel->save();
                $user_post->id_post = $postModel->id;
                $user_post->id_user = auth()->user()->id;
                $user_post->name_user = auth()->user()->name;
                $user_post->save();
                $this->loggingActivity(['name'=>'CREATE_ANNOUNCEMENT','subject_id'=> $announcementModel, 'description' => 'Create Announcement - '. $postModel->title]);
                $this->resetInput();
                return redirect()->route('announcement.title', ['title' => $postModel->seo_url])->with('success', 'Announcement has been posted! - '.$postModel->title);

        });
    }
    public function getPreview()
    {
        $this->preview = true;
        $this->descriptionPreview = $this->description;
        $this->thumbnailPreview = $this->thumbnail;
    }
}

app/Http/Livewire/Components/Announcement/PaginateAnnouncement.php
<?php

namespace App\Http\Livewire\Components\Announcement;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\{
    Posts, Dept, 
};

class PaginateAnnouncement extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $sortParam, $sortDir;
    public function getQueryString()
    {
        return [];
    }
    public function render()
    {   
        
        $announcement = Posts::select('posts.title', 'posts.seo_url', 'posts.created_at', 'announcements.thumbnail_path')
        ->join('announcements', 'announcements.id_post', '=','posts.id')
        ->orderBy('posts.'.(!is_null($this->sortParam) ? $this->sortParam : 'title'), 
            (!is_null($this->sortDir) ? $this->sortDir : 'ASC'))
        ->paginate(2);
        
        return view('livewire.components.announcement.paginate-announcement', compact('announcement'));
    }
}

app/Http/Livewire/Components/Hc/HcCornerCreate.php
<?php

namespace App\Http\Livewire\Components\Hc;

use Livewire\Component;
use Illuminate\Support\Facades\DB;
use Livewire\WithFileUploads;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Http\Traits\{TextProcessingTrait,LoggerTrait};
use App\Models\{Posts,HcCorner,PostUserRel, Dept};

class HcCornerCreate extends Component
{
    use WithFileUploads, TextProcessingTrait, LoggerTrait;

    public $title, $description, $thumbnail, $descriptionPreview, $thumbnailPreview;
    public $createdBy;
    public $preview = false;
    public function render()
    {
        return view('livewire.components.Hc.hc-corner-create');
    }
    protected $listeners = [
        'refresh-contents' => 'getContent'
    ];
    protected $rules = [
        'title' => 'required|unique:posts,title|max:255',
        'description' => 'required',
        'thumbnail' => 'required|mimes:jpg,jpeg,png|max:2048',
    ];
    private function resetInput()
    {
        $this->title = null;
        $this->description = null;
        $this->thumbnail = null;
        $this->descriptionPreview = null;
        $this->thumbnailPreview = null;
        $this->preview = false;
    }

    public function getContent($term)
    {
        $this->description= $term['content'];
    }
    public function getPreview()
    {
        $this->preview = true;
        $this->descriptionPreview = $this->description;
        $this->thumbnailPreview = $this->thumbnail;
    }

    public function submit()
    {
        $this->validate();
        $postModel = new Posts;
        $contentModel = new HcCorner;
        $user_post = new PostUserRel;

        DB::transaction(function () use (
            $postModel,$contentModel,$user_post)
            {
                $postModel->title = $this->title;
                $postModel->id_dept = Dept::where('dept_code', 'hcl')->firstOrfail()->id;
                $postModel->seo_url = $this->string_seo($this->title);
                $postModel->save();
                $fileName = $postModel->id.'-'.$this->seo_friendly_url($this->limit_text($this->title, 6));
                $dom = new \DomDocument();
                $dom->loadHtml($this->description, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
                $images = $dom->getElementsByTagName('img');
                foreach($images as $k => $img){
                    $data = $img->getAttribute('src');
                    list($type, $data) = explode(';', $data);
                    list(, $data)      = explode(',', $data);
                    $data = base64_decode($data);
                    $image_name = '/public/uploads/hc_corners/'.$fileName.'/contents'.'/'.
                    $fileName.'-'.time().$k.'.png';
                    $path = '/storage/uploads/hc_corners/'.$fileName.'/contents'.'/'.
                    $fileName.'-'.time().$k.'.png';
                    Storage::put($image_name, $data);
                    $img->removeAttribute('src');
                    $img->setAttribute('src', $path);
                }
                $this->description = $dom->saveHTML();
                $contentModel->contents = $this->description;
                $contentModel->id_post = $postModel->id;
                $this->thumbnail->storeAs('uploads/hc_corners/'.$fileName.'/thumbnail', 
                    $fileName.'.'.$this->thumbnail->getClientOriginalExtension(), 'public');
                $contentModel->thumbnail_path = '/storage/uploads/hc_corners/'.$fileName.'/thumbnail/'.
                $fileName.'.'.$this->thumbnail->getClientOriginalExtension();
                $contentModel->save();
                $user_post->id_post = $postModel->id;
                $user_post->id_user = auth()->user()->id;
                $user_post->name_user = auth()->user()->name;
                $user_post->save();
                $this->loggingActivity(['name'=>'CREATE_HC_CORNER','subject_id'=> $contentModel, 'description' => 'Create HC Corner -'. $postModel->title]);
                $this->resetInput();
                return redirect()->route('hc-corner.title', ['title' => $postModel->seo_url])->with('success', 'Content has been posted! '.$postModel->title);
            });
    }
}

app/Http/Livewire/Components/Hc/PaginateCorner.php
<?php

namespace App\Http\Livewire\Components\Hc;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\{
    Posts, Dept, 
};


class PaginateCorner extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $sortParam, $sortDir;
    public function getQueryString()
    {
        return [];
    }

    public function render()
    {
        $hcorners = Posts::select('posts.title', 'posts.seo_url', 'posts.created_at', 'hc_corners.thumbnail_path')
        ->join('hc_corners', 'hc_corners.id_post', '=','posts.id')
        ->orderBy('posts.'.(!is_null($this->sortParam) ? $this->sortParam : 'title'), 
            (!is_null($this->sortDir) ? $this->sortDir : 'ASC'))
        ->paginate(2);
        return view('livewire.components.Hc.paginate-corner', compact('hcorners'));
    }
}

app/Http/Livewire/Components/Landing/AnnouncementHome.php
<?php

namespace App\Http\Livewire\Components\Landing;

use Livewire\Component;
use App\Models\{Posts};

class AnnouncementHome extends Component
{
    public $file_path, $announcement_id, $title;
    public $allData;
    public function render()
    {
        $announcement = Posts::join('announcements', 'posts.id', '=', 'announcements.id_post')
        ->orderBy('announcements.created_at', 'desc')
        ->take(3)
        ->get();
        return view('livewire.landing.announcement-home', [
            'announcement' => $announcement,
        ]);
        
        // return view('livewire.announcement-home');
    }
}

resources/views/livewire/components/marcomm/create-matrix-tips.blade.php
<div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                  <h4 class="card-title">Preview</h4>  
                </div>
                <br>
                <div class="card-body">
                    @if ($preview == true)
                        {!! $description !!}
                    @endif
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
            <div class="col-md-12">
                <form wire:submit.prevent="submit" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title" wire:model.lazy="title" placeholder="Enter Title" required>
                        @error('title') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="chooseFile">Image Thumbnail</label>
                        <div class="input-group">
                          <div class="custom-file">
                            <label class="custom-file-label" for="chooseFile" x-data="{ files: null }">
                            <input type="file" class="sr-only" name="thumbnail" id="chooseFile" wire:model.lazy="thumbnail" x-on:change="files = Object.values($event.target.files)">
                            <span x-text="files ? files.map(file => file.name).join(', ') : 'Choose image..'"></span></label>
                            
                          </div>
                        </div>
                        @error('file') <span class="text-danger">{{ $message }}</span> @enderror
                    </div>
                    <div class="form-group" wire:ignore>
                        <textarea type="text" name="description" input="description" id="summernote" class="form-control summernote" wire:model="description">
                            {{ $description }}
                        </textarea>
                    </div>
                    <div>
                        <div class="row">
                            @if (session()->has('success'))
                            <div class="col-8">
                                <div class="alert alert-success">
                                    {{ session('success') }}
                                </div>
                            </div>
                            <script>
                                toastr.success('Lorem ipsum dolor sit amet, consetetur sadipscing elitr.')
                            </script>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-6">
                                <button class="btn btn-block btn-primary" type="submit">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-sm-3">
                        <button class="btn btn-block btn-warning" type="submit" wire:click="draft">
                            Save as Draft
                        </button>
                    </div>
                    <div class="col-sm-3">
                        <button class="btn btn-block btn-info " type="submit" wire:click="getPreview">
                            Preview
                        </button>
                    </div>
                </div>
            </div>
    
    </div>
</div>

resources/views/livewire/components/marcomm/paginate-tips.blade.php
<div>
    
    <section class="row">
        <div class="col-md-2">
            <select class="form-control" wire:model="sortParam">
                <option value="" hidden>Choose One</option>
                <option value="created_at">Created Date</option>
                <option value="title">Title</option>
            </select>

        </div>
        <div class="col-md-2">
            <select class="form-control" wire:model="sortDir">
                <option value="" hidden>Choose One</option>
                <option value="ASC">Ascending</option>
                <option value="DESC">Descending</option>
            </select>
        </div>
    </section>

    @foreach ($tips as $tp)
    <div class="row">
        <div class="col-md-6">
            <h2>
                <a href="{{route('tips.title',$tp->seo_url)}}" target="_blank" rel="noopener noreferrer">
                    {{$tp->title}}
                </a>
            </h2>
            <span>{{$tp->created_at->isoFormat('dddd, D MMMM Y')}}</span>
            <br>
            <a href="{{route('tips.title',$tp->seo_url)}}" class="btn btn-primary"  target="_blank" rel="noopener noreferrer">Read More</a>
        </div>
        <div class="col-md-6"  target="_blank" rel="noopener noreferrer">
            <a href="{{route('tips.title',$tp->seo_url)}}">
                <img src="{{url($tp->thumbnail_path)}}" alt=""/>
            </a>
            
        </div>
    </div> 
    @endforeach
    <div class="row">
        {{$tips->links() }} 
    </div> 
    
</div>